# Generated by Django 4.1.1 on 2022-10-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_likes",
            field=models.IntegerField(default=0),
        ),
    ]
