# Generated by Django 4.1.1 on 2022-10-24 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipe", "0002_delete_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingridient_name", models.CharField(max_length=255)),
                ("ingredient_quantity", models.CharField(blank=True, max_length=255)),
                (
                    "ingredient_date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipe.recipe",
                    ),
                ),
            ],
        ),
    ]
