# Generated by Django 4.1.1 on 2022-10-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="ingridient_name",
            new_name="ingredient_name",
        ),
    ]
