# Generated by Django 4.1.1 on 2022-10-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_delete_ingredient"),
        ("ingredient", "0002_rename_ingridient_name_ingredient_ingredient_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="ingredient", name="recipe",),
        migrations.AddField(
            model_name="ingredient",
            name="recipe",
            field=models.ManyToManyField(to="recipe.recipe"),
        ),
    ]
