# Generated by Django 4.1.1 on 2022-10-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0003_remove_ingredient_recipe_ingredient_recipe"),
    ]

    operations = [
        migrations.RemoveField(model_name="ingredient", name="recipe",),
    ]
