# Generated by Django 4.1.1 on 2022-10-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Ingredient",),
    ]
