# Generated by Django 4.1.1 on 2022-10-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0004_remove_ingredient_recipe"),
        ("recipe", "0002_delete_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredient",
            field=models.ManyToManyField(to="ingredient.ingredient"),
        ),
    ]
