# Generated by Django 4.1.1 on 2022-10-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
        ("recipe", "0004_rename_ingredient_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="comments",
            field=models.ManyToManyField(to="comment.comment"),
        ),
    ]
