# Generated by Django 4.1.1 on 2022-10-25 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0005_recipe_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikedRecipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=255, null=True)),
                (
                    "does_liked",
                    models.CharField(
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("NO_OPINION", "No Opinion"),
                        ],
                        default="NO_OPINION",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.ManyToManyField(to="recipe.likedrecipes"),
        ),
    ]
